### PR TITLE
Initial schedule.

### PR DESCRIPTION
**Pull request by johanneskoester**
@jbaaijens what do you think? Any constraints I forgot? I'll add the times once the order is final.

### CODE REVIEW

**Comment by jbaaijens** [comment]
@johanneskoester I think it looks nice, but we're missing 1 talk, namely by Ehsan Haghshenas on long read analysis (title and abstract yet to come). It would be best to have 8 talks on the first day, so maybe we can add Ehsan after Jouni, or at the very end (after Rayan)?

**Comment by jbaaijens** [comment]
@johanneskoester I've added a suggestion for the time slots, taking 10 minutes of the coffee break on the first day to allow for 10 minutes of 'arrival time' (9:00-9:10). What do you think?

**Comment by johanneskoester** [comment]
Yes, I had the same thought.

**Comment by johanneskoester** [comment]
Thanks!

**Pull request merged**
